name: Git Version

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'pull/**'
      - 'pull-request/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.10.3'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
        
  display-semver:
      name: Display Semantic Version
      runs-on: ubuntu-latest
      needs: lint
      env:
        SEMVER: ${{ needs.lint.outputs.semVer }}
      steps:
        - name: Display version
          run: |
            echo SemVer: $SEMVER
        
        - name: Create version file
          uses: actions/checkout@v3
        
        - name: Write version
          run: echo __version__="$SEMVER" > version.py
